dataprovider: # optional, preload: False
  preload: True
pipelines:
  - FollowLeadingVehicle_generated: # name will be used as output filename and overwritten in case it exists
      steps:
        - Scenario:
            name_prefix: FollowLeadingVehicle_generated # optional, default <type>-idx
            type: FollowLeadingVehicle # mandatory
        - Actor:
            per_scenario: 5 # optional, default 1
            tag: ego_vehicle # optional, default ego_vehicle
            positioning: # optional, default junctions: True, streets: True
              junctions: False
              streets: True
        - Weather:
            per_scenario: 5 # optional, default 1
