dataprovider: # optional, preload: False
  preload: False
pipeline:
  - Scenario:
      name: Test # optional, default <type>-idx
      type: Test # mandatory
  - Actor:
      per_scenario: 1 # optional, default 1
      tag: ego_vehicle # optional, default ego_vehicle
      positioning: # optional, default junctions: true, streets: true
        junctions: true
        streets: true
  - Weather:
      per_scenario: 1 # optional, default 1
