dataprovider: # optional, preload: False
  preload: True
pipelines:

  # 1 Scenario ControlLoss
  - ControlLoss_generated: # name will be used as output filename and overwritten in case it exists
    steps:
      - Scenario:
        name_prefix: ControlLoss_generated # optional, default <type>-idx
        type: ControlLoss # mandatory
      - Actor:
        per_scenario: 5 # optional, default 1
        tag: ego_vehicle # optional, default ego_vehicle
        positioning: # optional, default junctions: True, streets: True
          junctions: False
          streets: True
      - Weather:
        per_scenario: 5 # optional, default 1

  # 2 Scenario FollowLeadingVehicle
  - FollowLeadingVehicle_generated:
    steps:
      - Scenario:
        name_prefix: FollowLeadingVehicle_generated
        type: FollowLeadingVehicle
      - Actor:
        per_scenario: 5
        tag: ego_vehicle
        positioning:
          junctions: False
          streets: True
      - Weather:
        per_scenario: 5

  # 3 Scenario DynamicObjectCrossing
  - DynamicObjectCrossing_generated:
    steps:
      - Scenario:
        name_prefix: DynamicObjectCrossing_generated
        type: DynamicObjectCrossing
      - Actor:
        per_scenario: 5
        tag: ego_vehicle
        positioning:
          junctions: False
          streets: True
      - Weather:
        per_scenario: 5

  # 4.1 Scenario VehicleTurningRight !!! TBD: Only right turns are allowed
  - VehicleTurningRight_generated:
    steps:
      - Scenario:
        name_prefix: VehicleTurningRight_generated
        type: VehicleTurningRight
      - Actor:
        per_scenario: 5
        tag: ego_vehicle
        positioning:
          junctions: True
          streets: False
      - Weather:
        per_scenario: 5

  # 4.2 Scenario VehicleTurningLeft !!! TBD: Only left turns are allowed
  - VehicleTurningRight_generated:
    steps:
      - Scenario:
        name_prefix: VehicleTurningLeft_generated
        type: VehicleTurningLeft
      - Actor:
        per_scenario: 5
        tag: ego_vehicle
        positioning:
          junctions: True
          streets: False
      - Weather:
        per_scenario: 5
