dataprovider: # optional, preload: False
  preload: True
pipelines:
  # 1 Scenario ControlLoss
  - 1_ControlLoss_generated: # name will be used as output filename and overwritten in case it exists
      steps:
        - Scenario:
            name_prefix: ControlLoss_generated # optional, default <type>-idx
            type: ControlLoss # mandatory
        - Actor:
            per_scenario: 5 # optional, default 1
            tag: ego_vehicle # optional, default ego_vehicle
            type: vehicle # optional, default vehicle
            positioning: # optional, default junctions: True, streets: True
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset # chose from {random, random_preset} default: random_preset
            per_scenario: 5 # optional, default 1

  # 2.1 Scenario FollowLeadingVehicle
  - 2_1_FollowLeadingVehicle_generated:
      steps:
        - Scenario:
            name_prefix: FollowLeadingVehicle_generated
            type: FollowLeadingVehicle
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 2.2 Scenario FollowLeadingVehicleWithObstacle
  - 2_2_FollowLeadingVehicleWithObstacle_generated:
      steps:
        - Scenario:
            name_prefix: FollowLeadingVehicleWithObstacle_generated
            type: FollowLeadingVehicleWithObstacle
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
              junctions: False
              streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 3 Scenario DynamicObjectCrossing
  - 3_ObjectCrossing_generated:
      steps:
        - Scenario:
            name_prefix: DynamicObjectCrossing_generated
            type: DynamicObjectCrossing
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 4.1 Scenario VehicleTurningRight !!! TBD: Only right turns are allowed
  - 4_1_VehicleTurning_right_generated:
      steps:
        - Scenario:
            name_prefix: VehicleTurningRight_generated
            type: VehicleTurningRight
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 4.2 Scenario VehicleTurningLeft !!! TBD: Only left turns are allowed
  - 4_2_VehicleTurning_left_generated:
      steps:
        - Scenario:
            name_prefix: VehicleTurningLeft_generated
            type: VehicleTurningLeft
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 5 Scenario OtherLeadingVehicle
  - 5_LeadingVehicle_generated:
      steps:
        - Scenario:
            name_prefix: OtherLeadingVehicle_generated
            type: OtherLeadingVehicle
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 6 Scenario ManeuverOppositeDirection
  - 6_OppositeDirection_generated:
      steps:
        - Scenario:
            name_prefix: ManeuverOppositeDirection_generated
            type: ManeuverOppositeDirection
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 7 Scenario OppositeVehicleRunningRedLight !!! TBD: Other actor must come from left of right
  - 7_RunningRedLight_generated:
      steps:
        - Scenario:
            name_prefix: OppositeVehicleRunningRedLight_generated
            type: OppositeVehicleRunningRedLight
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions:
                  straight: True
                  left: False
                  right: False
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions:
                  straight: True
                  left: True
                  right: False
                  relative_to_ego:
                    straight: False
                    left: True
                    right: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 8 Scenario SignalizedJunctionLeftTurn !!! TBD: Other actor must come from straight ahead
  - 8_SignalizedJunctionLeftTurn_generated:
      steps:
        - Scenario:
            name_prefix: SignalizedJunctionLeftTurn_generated
            type: SignalizedJunctionLeftTurn
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions:
                  straight: False
                  left: True
                  right: False
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions:
                  straight: True
                  left: False
                  right: False
                  relative_to_ego:
                    straight: True
                    left: False
                    right: False
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 9 Scenario SignalizedJunctionRightTurn !!! TBD: Other actor must come from left
  - 9_SignalizedJunctionRightTurn_generated:
      steps:
        - Scenario:
            name_prefix: SignalizedJunctionRightTurn_generated
            type: SignalizedJunctionRightTurn
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions:
                  straight: False
                  left: False
                  right: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions:
                  straight: True
                  left: False
                  right: False
                  relative_to_ego:
                    straight: False
                    left: True
                    right: False
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 10 Scenario SignalizedJunctionRightTurn !!! TBD: Other actor must come from left
  - 10_NoSignalJunction_generated:
      steps:
        - Scenario:
            name_prefix: NoSignalJunctionCrossing_generated
            type: NoSignalJunctionCrossing
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions:
                  straight: True
                  left: True
                  right: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions:
                  straight: True
                  left: True
                  right: True
                  relative_to_ego:
                    straight: True
                    left: True
                    right: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5
