dataprovider: # optional, preload: False
  preload: True
pipelines:
  # 1 Scenario ControlLoss
  - ControlLoss_generated: # name will be used as output filename and overwritten in case it exists
      steps:
        - Scenario:
            name_prefix: ControlLoss_generated # optional, default <type>-idx
            type: ControlLoss # mandatory
        - Actor:
            per_scenario: 5 # optional, default 1
            tag: ego_vehicle # optional, default ego_vehicle
            positioning: # optional, default junctions: True, streets: True
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset # chose from {random, random_preset} default: random_preset
            per_scenario: 5 # optional, default 1

  # 2 Scenario FollowLeadingVehicle
  - FollowLeadingVehicle_generated:
      steps:
        - Scenario:
            name_prefix: FollowLeadingVehicle_generated
            type: FollowLeadingVehicle
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 3 Scenario DynamicObjectCrossing
  - ObjectCrossing_generated:
      steps:
        - Scenario:
            name_prefix: DynamicObjectCrossing_generated
            type: DynamicObjectCrossing
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 4.1 Scenario VehicleTurningRight !!! TBD: Only right turns are allowed
  - VehicleTurning_right_generated:
      steps:
        - Scenario:
            name_prefix: VehicleTurningRight_generated
            type: VehicleTurningRight
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 4.2 Scenario VehicleTurningLeft !!! TBD: Only left turns are allowed
  - VehicleTurning_left_generated:
      steps:
        - Scenario:
            name_prefix: VehicleTurningLeft_generated
            type: VehicleTurningLeft
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 5 Scenario OtherLeadingVehicle
  - LeadingVehicle_generated:
      steps:
        - Scenario:
            name_prefix: OtherLeadingVehicle_generated
            type: OtherLeadingVehicle
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 6 Scenario ManeuverOppositeDirection
  - OppositeDirection_generated:
      steps:
        - Scenario:
            name_prefix: ManeuverOppositeDirection_generated
            type: ManeuverOppositeDirection
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: False
                streets: True
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 7 Scenario OppositeVehicleRunningRedLight !!! TBD: Other actor must come from left of right
  - RunningRedLight_generated:
      steps:
        - Scenario:
            name_prefix: OppositeVehicleRunningRedLight_generated
            type: OppositeVehicleRunningRedLight
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 8 Scenario SignalizedJunctionLeftTurn !!! TBD: Other actor must come from straight ahead
  - SignalizedJunctionLeftTurn_generated:
      steps:
        - Scenario:
            name_prefix: SignalizedJunctionLeftTurn_generated
            type: SignalizedJunctionLeftTurn
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 9 Scenario SignalizedJunctionRightTurn !!! TBD: Other actor must come from left
  - SignalizedJunctionRightTurn_generated:
      steps:
        - Scenario:
            name_prefix: SignalizedJunctionRightTurn_generated
            type: SignalizedJunctionRightTurn
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5

  # 10 Scenario SignalizedJunctionRightTurn !!! TBD: Other actor must come from left
  - NoSignalJunction_generated:
      steps:
        - Scenario:
            name_prefix: NoSignalJunctionCrossing_generated
            type: NoSignalJunctionCrossing
        - Actor:
            per_scenario: 5
            tag: ego_vehicle
            positioning:
                junctions: True
                streets: False
        - Actor:
            per_scenario: 5
            tag: other_actor
            positioning:
                junctions: True
                streets: False
        - Weather:
            generation_type: random_preset
            per_scenario: 5
