from pathlib import Path
import time

from xml.etree.ElementTree import Comment

from core.xml.utils import get_pretty_xml
from core.logger.logger import logger


def write_xml(tree, filename=None, path="output/", ):
    """Creates an output folder, and writes a given xml-tree to the file system with predefined defaults

    :param tree: XML-tree
    :type tree: object
    :param filename: Filename for the file to write
    :type filename: str
    :param path: Path to write the file to
    :type path: str
    """
    if filename is None:
        filename = "scenario_output_" + time.strftime("%Y%m%d-%H%M%S") + ".xml"
    if not filename.endswith(".xml"):
        filename += ".xml"
    if not path.endswith("/"):
        path += "/"
    if path.startswith("/"):
        path = path[1:]

    create_output_folder(path)
    write_tree(tree, path, filename)


def write_tree(tree, path, filename):
    """Writes a given xml-tree to the file system

    If the file with the filename already exists it will be overridden

    :param tree: XML-tree
    :type tree: object
    :param filename: Filename for the file to write
    :type filename: str
    :param path: Path to write the file to
    :type path: str
    """
    logger.debug("Writing XML file...")
    path_to_file = path + filename
    add_generator_comment(tree)
    pretty_xml = get_pretty_xml(tree)
    with open(path_to_file, "w") as f:
        f.write(pretty_xml)
    logger.debug("Done writing XML file")


def add_generator_comment(tree, comment="Auto Generated By Pre Crash Scenario Generator"):
    """Given a xml-tree, it will add a comment to the top of the root element

    :param tree: XML-tree
    :type tree: object
    :param comment: Comment to write into the xml-tree
    :type comment: str
    """
    root = tree.getroot()
    root.insert(0, Comment(comment))


def create_output_folder(path):
    """Creates a new folder and its parents given a path

    :param path: The path where the folder should be created
    :type path: str
    """
    Path(path).mkdir(parents=True, exist_ok=True)
