from xml.etree.ElementTree import Element, Comment, ElementTree


def initialize_xml_tree():
    root = Element("scenarios")
    root.append(
        Comment("Auto Generated By Pre Crash Scenario Generator"))
    return ElementTree(root)
